# Generated by Django 5.1.7 on 2025-03-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Catagory',
        ),
        migrations.AlterModelTable(
            name='maincategory',
            table='MainCat',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
